# Generated by Django 2.2.6 on 2020-09-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetscreenshot',
            name='optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presetscreenshot',
            name='comparison_image',
            field=models.ImageField(blank=True, help_text='Optional comparison image, where SweetFX is OFF', null=True, upload_to='presetscreenshotscompare/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='presetscreenshot',
            name='image',
            field=models.ImageField(height_field='image_height', help_text='The main image, the screenshot itself', upload_to='presetscreenshots/%Y/%m/%d/', verbose_name='SweetFX image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='presetscreenshot',
            name='medium_thumb',
            field=models.ImageField(upload_to='medthumb/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='presetscreenshot',
            name='medium_thumb_compared',
            field=models.ImageField(blank=True, null=True, upload_to='medthumb/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='presetscreenshot',
            name='small_thumb',
            field=models.ImageField(upload_to='smallthumb/%Y/%m/%d/'),
        ),
    ]
