# Generated by Django 2.2.6 on 2025-02-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0002_auto_20200920_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'permissions': [('post_on_games', 'Can post on games')]},
        ),
    ]
