# Generated by Django 2.2.6 on 2025-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0003_auto_20250211_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Visible'), (2, 'Spam'), (3, 'Unsure'), (4, 'Error'), (5, 'Verified spam'), (6, 'Mistaken for spam')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='state_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preset',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Visible'), (2, 'Spam'), (3, 'Unsure'), (4, 'Error'), (5, 'Verified spam'), (6, 'Mistaken for spam')], default=0),
        ),
        migrations.AddField(
            model_name='preset',
            name='state_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
