# Generated by Django 2.2.6 on 2019-10-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sortweight', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sortweight', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlfile', models.FileField(upload_to='downloads')),
                ('name', models.CharField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('sortweight', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.DownloadCategory')),
            ],
            options={
                'ordering': ['sortweight', '-id'],
            },
        ),
    ]
