# Generated by Django 2.2.6 on 2020-09-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['created']},
        ),
    ]
