# Generated by Django 2.2.6 on 2025-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200920_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-sorting'], 'permissions': [('post_on_forum', 'Can post on forum')]},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Visible'), (2, 'Spam')], default=0),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='state',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Visible')], default=1),
        ),
    ]
