# Generated by Django 2.2.6 on 2025-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20250210_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='state_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Visible'), (2, 'Spam'), (3, 'Unsure')], default=0),
        ),
    ]
