# Generated by Django 2.2.6 on 2025-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20250212_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Visible'), (2, 'Spam'), (3, 'Unsure'), (4, 'Error'), (5, 'Verified spam'), (6, 'Mistaken for spam')], default=0),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
