# Generated by Django 2.2.6 on 2019-10-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sweetfx_database.gamedb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('css', models.CharField(blank=True, help_text='CSS url for the theme', max_length=255, verbose_name='CSS url')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('css', models.CharField(blank=True, help_text='Custom CSS url to use on the site', max_length=255, verbose_name='CSS url')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(sweetfx_database.gamedb.models.RenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PresetFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gamedb.Preset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('preset', 'user')},
            },
        ),
    ]
